import React from "react";
import "./Feed.css";

function Feed() {
    return (
        <section className="feed">
            <h1>test</h1>
            <p>wd</p>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
            <h2>yoooooooooo</h2>
        </section>
    );
}

export default Feed;
